# Generated by Django 4.0.1 on 2022-04-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('receiver_address', models.EmailField(max_length=254)),
                ('sender_address', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('attatchment', models.FileField(upload_to='emails/attatchments/')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.email')),
            ],
            options={
                'ordering': ('-date_sent',),
            },
        ),
    ]
