# Generated by Django 4.0.1 on 2022-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='unread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='attatchment',
            field=models.FileField(blank=True, null=True, upload_to='emails/attatchments/'),
        ),
    ]
