# Generated by Django 4.0.1 on 2022-03-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='picker_rating',
            field=models.IntegerField(default=0),
        ),
    ]
