# Generated by Django 4.0.1 on 2022-03-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_distribution_picker_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ('-date_posted',)},
        ),
    ]
