# Generated by Django 4.0.1 on 2022-04-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-like', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('-like', '-created_at')},
        ),
    ]
