# Generated by Django 4.0.1 on 2022-03-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_solution', models.TextField(blank=True, null=True)),
                ('file_solution', models.FileField(blank=True, null=True, upload_to='solutions/')),
                ('solution_result', models.IntegerField(default=0)),
                ('presession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='presessions.presession')),
            ],
        ),
    ]
