# Generated by Django 4.0.1 on 2022-03-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
