# Generated by Django 4.0.1 on 2022-03-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_solution_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['presession']},
        ),
    ]
